create table if not exists zoos.objects (
    id bigint generated by default as identity not null primary key,
    name text not null,
    description text null,
    owner_email text not null,
    object_type text not null,
    access_read text[] default array[]::text[] not null,
    access_write text[] default array[]::text[] not null,
    access_manage text[] default array[]::text[] not null,
    object_data jsonb not null,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null,
    update_email text not null
);

alter table zoos.objects enable row level security;
drop policy if exists "select" on zoos.objects;
create policy "select" on zoos.objects for select using (auth.email() = owner_email or auth.email() = any(access_read));
